#165305223 Users should be able to Login to Authors Haven
andela/ah-the-jedi-frontend pull request #12
Opened 2019-05-31 08:30 UTC by Benkimeric

#### What does this PR do?
- Implements user functionality to allow a user to login

#### Description of Task to be completed?
- Add functionality to log in a user
- Add functionality to log out a user

#### How should this be manually tested?

- [x] **Clone the repository**

        $ git clone https://github.com/andela/ah-the-jedi-frontend.git

- [x] **Switch to testing branch**

       $ git checkout ft-user-login-165305223

- [x] **Switch to the ah-the-jedi-frontend directory**

       $ cd ah-the-jedi-frontend/

 
- [x] **Install the project dependencies**

      $  npm install

- [x] **Running the project**

       $ npm start

- [x] **Navigate to the login page**

       $ <your-localhost>/login
     

#### What are the relevant pivotal tracker stories?
[#165305223](https://www.pivotaltracker.com/story/show/165305223)
#### Any background context you want to add?
None
#### Screenshots

#### Successful Login
![Login Success](https://user-images.githubusercontent.com/19903559/58691073-ae58d800-8393-11e9-895d-96d4012ab924.gif)

#### Unsuccessful on login
![Login error](https://user-images.githubusercontent.com/19903559/58691094-bc0e5d80-8393-11e9-9717-bed26b5b19e0.gif)

2019-06-03 18:46 UTC, ElishaMisoi requested changes
Good implementation @Benkimeric 👍🏽. You should however squash your commits.

2019-06-03 19:04 UTC, AlvinMugambi approved these changes
Great implementation. Good work on styling the login box.

2019-06-03 20:06 UTC, ElishaMisoi approved these changes

2019-06-03 20:54 UTC, katherine95 approved these changes
LGTM

2019-06-04 03:35 UTC, Siffersari approved these changes
Good job. I love the use of toasts to display the error messages and the use of loader to show that the request is underway. Great implementation for deactivated login button for validation. Really intuitive.

2019-06-04 07:50 UTC, AnguleMathias requested changes
Great job @Benkimeric on implementing the feature, kindly check on the comments

2019-06-04 07:50 UTC, AnguleMathias commented on src/assets/styles/login.scss
> +    margin-bottom: 4%;
Move line `47-48` to be on line `39`

2019-06-04 07:50 UTC, AnguleMathias commented on src/assets/styles/login.scss
> +      -moz-box-shadow: 1px 2px 4px rgba(0, 0, 0, 0.5);
Store the color spaces in a `variables.scss` file and import the variable name

2019-06-04 07:50 UTC, AnguleMathias commented on src/components/App.js
> +import 'react-toastify/dist/ReactToastify.css';
move this to line 4

2019-06-04 07:50 UTC, AnguleMathias commented on src/components/auth/LoginForm.js
> +import '../../assets/styles/login.scss';
move down to line 4

2019-06-04 07:50 UTC, AnguleMathias commented on src/components/layout/LoggedInLinks.js
> +class LoggedInLinks extends React.Component {
Add documentation eg
```
/*
* LoggedInLinks Component
*
*@return {jsx}
*/

```

2019-06-04 07:50 UTC, AnguleMathias commented on tests/App.test.jsx
>  describe('PASSES', () => {
Have the describe as:
`Unit tests for App Component`

2019-06-04 07:50 UTC, AnguleMathias commented on tests/LoggedInLinks.test.jsx
> +  describe('Test for the Header component <LoggedInLinks />', () => {
have it as:

`Unit tests for Header Component`

2019-06-04 07:50 UTC, AnguleMathias commented on tests/LoggedInLinks.test.jsx
> +    it('Should render component without errors', () => {
it should render nav-bar-test

2019-06-04 08:48 UTC, jkamz approved these changes

2019-06-04 13:25 UTC, ElishaMisoi approved these changes

2019-06-04 13:29 UTC, merged